# Shell
shell /usr/bin/zsh

# Font
font_family MartianMono Nerd Font Mono
bold_font MatianMono Nerd Font Mono Bold
italic_font MartianMono Nerd Font Mono Italic
bold_italic_font MartianMono Nerd Font Mono Bold Italic
font_size 18.0

# Window
hide_window_decorations no
remember_window_size yes
wayland_titlebar_color default

# Cursor
cursor_shape block
cursor_blink_interval 0.6
shell_integration no-cursor

# Theme
foreground            #ffffff
background            #101010
selection_foreground  #101010
selection_background  #ffffff
url_color             #777777

# Cursor
cursor                #ffffff
cursor_text_color     #101010

# ANSI Colors (Grayscale)
color0  #101010
color8  #333333
color1  #ffffff
color9  #ffffff
color2  #cccccc
color10 #cccccc
color3  #999999
color11 #999999
color4  #bbbbbb
color12 #bbbbbb
color5  #eeeeee
color13 #eeeeee
color6  #888888
color14 #888888
color7  #ffffff
color15 #ffffff

