# Disable shadows
shadow = false;

# Disable transparency
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;

# Fading disabled
fading = false;

# VSync on
vsync = true;

# Backend
backend = "glx";

# Exclusions
shadow-exclude = [
    "window_type = 'popup_menu'",
    "window_type = 'dropdown_menu'",
    "window_type = 'tooltip'",
    "window_type = 'combo'",
    "window_type = 'dnd'",
    "window_type = 'utility'"
];

detect-client-opacity = false;
detect-transient = true;
detect-rounded-corners = true;
